name: Code Scan

on:
  push:
    branches: [main]

jobs:
  linter:
    # server
    runs-on: ubuntu-latest

    steps:
      # get the latest code in the server
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
           python-version: "3.12"

      - name: install linter flake8
        run: pip install flake8

      - name: scan code for syntax
        run: flake8 app.py
  
